-- DROP SEQUENCE public.accounts_uid_seq;

CREATE SEQUENCE public.accounts_uid_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.blogs_blog_id_seq;

CREATE SEQUENCE public.blogs_blog_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;-- public.accounts definition

-- Drop table

-- DROP TABLE public.accounts;

CREATE TABLE public.accounts (
	uid serial NOT NULL,
	"name" varchar(50) NOT NULL,
	"password" varchar(50) NOT NULL,
	email varchar(255) NOT NULL,
	created_on timestamp NOT NULL,
	last_login timestamp NULL,
	"role" varchar(2) NOT NULL DEFAULT 'GU'::character varying,
	CONSTRAINT accounts_email_key UNIQUE (email),
	CONSTRAINT accounts_pkey PRIMARY KEY (uid),
	CONSTRAINT accounts_un UNIQUE (uid)
);


-- public.blogs definition

-- Drop table

-- DROP TABLE public.blogs;

CREATE TABLE public.blogs (
	blog_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	title varchar(255) NOT NULL,
	body text NOT NULL,
	author int4 NOT NULL,
	updated_on timestamp NOT NULL,
	CONSTRAINT blogs_pk PRIMARY KEY (blog_id),
	CONSTRAINT blogs_fk FOREIGN KEY (author) REFERENCES public.accounts(uid)
);


