version: "3.9"
services: 
  db:
    image: postgres
    restart: always
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: aadarsha
      POSTGRES_PASSWORD: ad
      POSTGRES_DB: aadarsha
      

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis
    restart: always
    ports: 
      - 6379:6379

  volumes:
    - .:/runtime
    -

  

  # dartserverstarter:
  #   image: dartserverstarter
  #   restart: always
  #   ports: 
  #     - 8000:8000