name: dartserverstarter
description: A web server built using the shelf package.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.0.0
  crypto: ^3.0.1
  dartz: ^0.10.0-nullsafety.2
  path: ^1.8.0
  postgresql2: ^1.0.1
  shelf_cors_headers: ^0.1.1
  shelf_hotreload: ^0.0.2
  shelf_router: ^1.0.0
  shelf_static: ^1.0.0
  validators: ^3.0.0

dev_dependencies:
  pedantic: ^1.10.0
  dio: ^4.0.0
  test: ^1.17.7
